### PR TITLE
upgrading grpc to 1.23.0

### PR DESCRIPTION
**Pull request by yuriabrito**

### CODE REVIEW

**Comment by andrehp** [comment]
What's the version of your mockgen?

**Comment by yuriabrito** [comment]
1.3.1, should I be using another?

**Comment by andrehp** [comment]
No, the version is fine, but you should probably update the Gopkg.lock to reflect the updated mock version.

**Comment by yuriabrito** [comment]
@andrehp makes sense! done :)

**Review by andrehp — APPROVED** [review]
LGTM

**Pull request merged**
